# Generated by Django 5.2.7 on 2025-10-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "content",
                    models.TextField(
                        help_text="'$' 구분자를 사용하여 작성 (예: Hello, $name!)"
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        blank=True, help_text="시스템 프롬프트 (선택사항)", null=True
                    ),
                ),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("max_tokens", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
